STP_COUNT = 1
G_START = 4
G_COUNT = 5
BG_START = 2
BG_COUNT = 5

localrules: all

rule all:
    input:
        'finish.npy'

rule analysis:
    input:
        ai = expand('scans/{a}_{b}_{c}/', a=range(STP_COUNT), b=range(G_START, G_START + G_COUNT), c=range(BG_START, BG_START + BG_COUNT))
    output:
        'finish.npy'

    shell:
        '''
        python analysis_g_bg.py {input.ai} {output}
        '''


