TEST_START = 1
TEST_COUNT = 1
G_START = 4
G_COUNT = 5
BG_START = 2
BG_COUNT = 5

localrules: all

rule all:
    input:
        'fr.png'

rule analysis:
    input:
        ai = expand('scans/{a}_{b}_{c}/', a=range(TEST_START, TEST_START + TEST_COUNT), b=range(G_START, G_START + G_COUNT), c=range(BG_START, BG_START + BG_COUNT))
    output:
        'fr.png'

    shell:
        '''
        python analysis_ground_state.py {input.ai} {output}
        '''
