F1_COUNT = 1
F2_COUNT = 1
G_START = 4
G_STEP = 1
G_END = 10
BG_START = 2
BG_STEP = 1
BG_END = 8

localrules: all

rule all:
    input:
        'none.png'

rule analysis:
    input:
        ai = expand('scans/{a}_{b}_{c}_{d}/', a=range(F1_COUNT), b=range(F2_COUNT), c=range(G_START, G_END + G_STEP, G_STEP), d=range(BG_START, BG_END + BG_STEP, BG_STEP))
    output:
        'none.png'

    shell:
        '''
        python analysis_ground_state.py {input.ai} {output} {G_START} {G_END} {G_STEP} {BG_START} {BG_END} {BG_STEP}
        '''
